<?php
    session_start();
    if(isset($_SESSION['username']))
    {
        $username=$_SESSION['username'];
    }
    else
    {
        echo'<script>
                window.open("index.php","_self");
            </script>';
    }
?>